#!/bin/sh
set -e

echo "Activating feature 'container-firewall'"

PROFILE="${PROFILE:-claude-code}"
CUSTOM_DOMAINS="${CUSTOMDOMAINS:-}"
BLOCK_TELEMETRY="${BLOCKTELEMETRY:-false}"
POLICY="${POLICY:-whitelist}"

# Install dependencies
install_deps() {
    if command -v apt-get >/dev/null 2>&1; then
        apt-get update
        apt-get install -y --no-install-recommends iptables ipset dnsutils curl jq aggregate
        apt-get clean
        rm -rf /var/lib/apt/lists/*
    elif command -v apk >/dev/null 2>&1; then
        apk add --no-cache iptables ipset bind-tools curl jq aggregate
    elif command -v yum >/dev/null 2>&1; then
        yum install -y iptables ipset bind-utils curl jq aggregate
    elif command -v dnf >/dev/null 2>&1; then
        dnf install -y iptables ipset bind-utils curl jq aggregate
    else
        echo "ERROR: could not install firewall dependencies"
        exit 1
    fi
}

if ! command -v iptables >/dev/null 2>&1 || ! command -v ipset >/dev/null 2>&1 || ! command -v dig >/dev/null 2>&1 || ! command -v curl >/dev/null 2>&1 || ! command -v jq >/dev/null 2>&1; then
    echo "Installing firewall dependencies..."
    install_deps
fi

SCRIPT_PATH="/usr/local/bin/container-firewall-init"

# Write the runtime firewall application script with baked-in options.
# These values are set at build time from the feature options.
cat > "$SCRIPT_PATH" << EOF
#!/bin/sh
set -e

# container-firewall-init — runtime firewall configuration
# This script is generated by the container-firewall devcontainer feature.
# It requires root and CAP_NET_ADMIN to run successfully.

PROFILE="$PROFILE"
CUSTOM_DOMAINS="$CUSTOM_DOMAINS"
BLOCK_TELEMETRY="$BLOCK_TELEMETRY"
POLICY="$POLICY"

# Verify iptables is usable (requires CAP_NET_ADMIN)
if ! iptables -L >/dev/null 2>&1; then
    echo "WARNING: iptables is not functional in this environment (missing CAP_NET_ADMIN)."
    echo "         Ensure the devcontainer feature declares capAdd: [\"NET_ADMIN\"], or add"
    echo "         --cap-add NET_ADMIN to your devcontainer.json runArgs."
    exit 0
fi

# 1. Extract Docker DNS before flushing
DOCKER_DNS_RULES=""
if command -v iptables-save >/dev/null 2>&1; then
    DOCKER_DNS_RULES=\$(iptables-save -t nat 2>/dev/null | grep "127\\.0\\.0\\.11" || true)
fi

iptables -F 2>/dev/null || true
iptables -X 2>/dev/null || true
iptables -t nat -F 2>/dev/null || true
iptables -t nat -X 2>/dev/null || true
iptables -t mangle -F 2>/dev/null || true
iptables -t mangle -X 2>/dev/null || true
ipset destroy allowed-domains 2>/dev/null || true
ipset destroy blocked-domains 2>/dev/null || true

# 2. Restore Docker DNS
if [ -n "\$DOCKER_DNS_RULES" ]; then
    echo "Restoring Docker DNS rules..."
    iptables -t nat -N DOCKER_OUTPUT 2>/dev/null || true
    iptables -t nat -N DOCKER_POSTROUTING 2>/dev/null || true
    echo "\$DOCKER_DNS_RULES" | while read -r line; do
        [ -z "\$line" ] && continue
        eval "iptables -t nat \$line" 2>/dev/null || true
    done
fi

# 3. Base allowances
iptables -A OUTPUT -p udp --dport 53 -j ACCEPT
iptables -A INPUT -p udp --sport 53 -j ACCEPT
iptables -A OUTPUT -p tcp --dport 22 -j ACCEPT
iptables -A INPUT -p tcp --sport 22 -m state --state ESTABLISHED -j ACCEPT
iptables -A INPUT -i lo -j ACCEPT
iptables -A OUTPUT -o lo -j ACCEPT

ipset create allowed-domains hash:net

if [ "\$BLOCK_TELEMETRY" = "true" ]; then
    ipset create blocked-domains hash:net
fi

# 4. Build domain list from preset
CLY_DOMAINS=""
TELEMETRY_DOMAINS="statsig.anthropic.com statsig.com sentry.io google-analytics.com doubleclick.net facebook.com googletagmanager.com"

resolve_and_add() {
    _domain="\$1"
    _ipset="\$2"
    echo "Resolving \$_domain..."
    _ips=\$(dig +noall +answer A "\$_domain" | awk '\$4 == "A" {print \$5}')
    if [ -z "\$_ips" ]; then
        echo "WARNING: Failed to resolve \$_domain"
        return 0
    fi
    echo "\$_ips" | while read -r _ip; do
        [ -z "\$_ip" ] && continue
        ipset add "\$_ipset" "\$_ip" 2>/dev/null || true
    done
}

case "\$PROFILE" in
    claude-code)
        CLY_DOMAINS="registry.npmjs.org api.anthropic.com marketplace.visualstudio.com vscode.blob.core.windows.net update.code.visualstudio.com"
        ;;
    github-only)
        CLY_DOMAINS=""
        ;;
    minimal)
        CLY_DOMAINS=""
        ;;
    custom)
        CLY_DOMAINS=\$(printf '%s' "\$CUSTOM_DOMAINS" | tr ',' ' ')
        ;;
    *)
        echo "ERROR: unknown profile '\$PROFILE'"
        exit 1
        ;;
esac

# 5. GitHub dynamic IPs (for claude-code and github-only profiles)
if [ "\$PROFILE" = "claude-code" ] || [ "\$PROFILE" = "github-only" ]; then
    echo "Fetching GitHub IP ranges..."
    gh_ranges=\$(curl -s --connect-timeout 10 https://api.github.com/meta || true)
    if [ -z "\$gh_ranges" ]; then
        echo "WARNING: Failed to fetch GitHub IP ranges"
    else
        if echo "\$gh_ranges" | jq -e '.web and .api and .git' >/dev/null 2>&1; then
            echo "\$gh_ranges" | jq -r '(.web + .api + .git)[]' | while read -r cidr; do
                [ -z "\$cidr" ] && continue
                case "\$cidr" in
                    [0-9]*.[0-9]*.[0-9]*.[0-9]*/[0-9]*)
                        ipset add allowed-domains "\$cidr" 2>/dev/null || true
                        ;;
                    *)
                        echo "WARNING: Skipping invalid CIDR from GitHub meta: \$cidr"
                        ;;
                esac
            done
        else
            echo "WARNING: GitHub API response missing expected fields"
        fi
    fi
fi

# 6. Resolve and add preset/custom domains to allowed set
for domain in \$CLY_DOMAINS; do
    [ -z "\$domain" ] && continue
    if [ "\$BLOCK_TELEMETRY" = "true" ] && [ "\$PROFILE" = "claude-code" ]; then
        _skip=""
        for _td in \$TELEMETRY_DOMAINS; do
            if [ "\$domain" = "\$_td" ]; then
                _skip="1"
                break
            fi
        done
        if [ "\$_skip" = "1" ]; then
            echo "Skipping telemetry domain from allow list: \$domain"
            continue
        fi
    fi
    resolve_and_add "\$domain" "allowed-domains"
done

# 7. Block telemetry domains if requested
if [ "\$BLOCK_TELEMETRY" = "true" ]; then
    echo "Blocking telemetry domains..."
    for domain in \$TELEMETRY_DOMAINS; do
        resolve_and_add "\$domain" "blocked-domains"
    done
fi

# 8. Host network detection
HOST_IP=\$(ip route 2>/dev/null | grep default | awk '{print \$3}' | head -n 1)
if [ -n "\$HOST_IP" ]; then
    HOST_NETWORK=\$(printf '%s' "\$HOST_IP" | sed 's/\\.[0-9]*\$/.0\\/24/')
    echo "Host network detected as: \$HOST_NETWORK"
    iptables -A INPUT -s "\$HOST_NETWORK" -j ACCEPT
    iptables -A OUTPUT -d "\$HOST_NETWORK" -j ACCEPT
fi

# 9. Apply policy
if [ "\$POLICY" = "whitelist" ]; then
    if [ "\$BLOCK_TELEMETRY" = "true" ]; then
        iptables -I OUTPUT -m set --match-set blocked-domains dst -j DROP
    fi

    iptables -P INPUT DROP
    iptables -P FORWARD DROP
    iptables -P OUTPUT DROP

    iptables -A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT
    iptables -A OUTPUT -m state --state ESTABLISHED,RELATED -j ACCEPT

    iptables -A OUTPUT -m set --match-set allowed-domains dst -j ACCEPT
    iptables -A OUTPUT -j REJECT --reject-with icmp-admin-prohibited
    echo "Firewall configured in whitelist mode"
else
    if [ "\$BLOCK_TELEMETRY" = "true" ]; then
        iptables -I OUTPUT -m set --match-set blocked-domains dst -j DROP
    fi
    iptables -A OUTPUT -m set ! --match-set allowed-domains dst -j LOG --log-prefix "FIREWALL-DROP: " --log-level 4
    echo "Firewall configured in monitor mode (logging only)"
fi

echo "Container firewall activation complete"
EOF

chmod +x "$SCRIPT_PATH"

echo "Container Firewall feature installed"
echo "Firewall rules will be applied automatically at container start via postStartCommand"
