#!/bin/sh
set -e

echo "Activating feature 'container-firewall'"

SERVICES="${SERVICES:-minimal}"
EXTRADOMAINS="${EXTRADOMAINS:-}"
BLOCKTELEMETRY="${BLOCKTELEMETRY:-false}"
POLICY="${POLICY:-whitelist}"
ENABLEIPV6="${ENABLEIPV6:-true}"

# Install dependencies using distro-specific package managers.
install_deps() {
    if command -v apt-get >/dev/null 2>&1; then
        apt-get update
        apt-get install -y --no-install-recommends iptables ipset dnsutils curl jq aggregate sudo iproute2 ca-certificates
        if ! command -v ip6tables >/dev/null 2>&1; then
            apt-get install -y --no-install-recommends ip6tables || true
        fi
        apt-get clean
        rm -rf /var/lib/apt/lists/*
    elif command -v apk >/dev/null 2>&1; then
        apk add --no-cache iptables ipset bind-tools curl jq aggregate sudo iproute2 ca-certificates
        if ! command -v ip6tables >/dev/null 2>&1; then
            apk add --no-cache ip6tables || true
        fi
    elif command -v yum >/dev/null 2>&1; then
        yum install -y iptables ipset bind-utils curl jq aggregate sudo iproute ca-certificates
        if ! command -v ip6tables >/dev/null 2>&1; then
            yum install -y ip6tables || true
        fi
    elif command -v dnf >/dev/null 2>&1; then
        dnf install -y iptables ipset bind-utils curl jq aggregate sudo iproute ca-certificates
        if ! command -v ip6tables >/dev/null 2>&1; then
            dnf install -y ip6tables || true
        fi
    else
        echo "ERROR: could not install firewall dependencies"
        exit 1
    fi
}

if ! command -v iptables >/dev/null 2>&1 \
    || ! command -v ipset >/dev/null 2>&1 \
    || ! command -v dig >/dev/null 2>&1 \
    || ! command -v curl >/dev/null 2>&1 \
    || ! command -v jq >/dev/null 2>&1 \
    || { [ "$ENABLEIPV6" = "true" ] && ! command -v ip6tables >/dev/null 2>&1; }; then
    echo "Installing firewall dependencies..."
    install_deps
fi

# Locate the service registry shipped with the feature and install it
# where the runtime script can read it.
SCRIPT_DIR=$(cd "$(dirname "$0")" && pwd)
REGISTRY_SRC="$SCRIPT_DIR/services.json"
REGISTRY_DST="/usr/local/share/container-firewall/services.json"

mkdir -p "$(dirname "$REGISTRY_DST")"
cp "$REGISTRY_SRC" "$REGISTRY_DST"

SCRIPT_PATH="/usr/local/bin/container-firewall-init"
TMP_RUNTIME=$(mktemp)

trap 'rm -f "$TMP_RUNTIME"' EXIT

# Write the runtime firewall application script.  Placeholders are replaced
# with the build-time option values after the heredoc is written.
cat > "$TMP_RUNTIME" <<'RUNTIMEEOF'
#!/bin/sh
set -e

# container-firewall-init — runtime firewall configuration
# Generated by the container-firewall devcontainer feature.
# It requires root and CAP_NET_ADMIN to run successfully.

SERVICES="__SERVICES__"
EXTRADOMAINS="__EXTRADOMAINS__"
BLOCKTELEMETRY="__BLOCKTELEMETRY__"
POLICY="__POLICY__"
ENABLEIPV6="__ENABLEIPV6__"

REGISTRY="/usr/local/share/container-firewall/services.json"

TELEMETRY_DOMAINS="statsig.anthropic.com statsig.com sentry.io google-analytics.com doubleclick.net facebook.com googletagmanager.com"

# Verify iptables is usable (requires CAP_NET_ADMIN)
if ! iptables -L >/dev/null 2>&1; then
    echo "WARNING: iptables is not functional in this environment (missing CAP_NET_ADMIN)."
    echo "         Ensure the devcontainer feature declares capAdd: [\"NET_ADMIN\"], or add"
    echo "         --cap-add NET_ADMIN to your devcontainer.json runArgs."
    exit 0
fi

if [ "$ENABLEIPV6" = "true" ]; then
    if ! ip6tables -L >/dev/null 2>&1; then
        echo "WARNING: ip6tables is not functional in this environment (missing CAP_NET_ADMIN or no IPv6 support)."
        echo "         Continuing with IPv4-only firewall."
        ENABLEIPV6=false
    fi
fi

# 1. Extract Docker DNS rules before flushing
DOCKER_DNS_RULES=""
if command -v iptables-save >/dev/null 2>&1; then
    DOCKER_DNS_RULES=$(iptables-save -t nat 2>/dev/null | grep "127\.0\.0\.11" || true)
fi

DOCKER_DNS_RULES_V6=""
if [ "$ENABLEIPV6" = "true" ]; then
    if command -v ip6tables-save >/dev/null 2>&1; then
        DOCKER_DNS_RULES_V6=$(ip6tables-save -t nat 2>/dev/null | grep "::11" || true)
    fi
fi

iptables -F 2>/dev/null || true
iptables -X 2>/dev/null || true
iptables -t nat -F 2>/dev/null || true
iptables -t nat -X 2>/dev/null || true
iptables -t mangle -F 2>/dev/null || true
iptables -t mangle -X 2>/dev/null || true

if [ "$ENABLEIPV6" = "true" ]; then
    ip6tables -F 2>/dev/null || true
    ip6tables -X 2>/dev/null || true
    ip6tables -t nat -F 2>/dev/null || true
    ip6tables -t nat -X 2>/dev/null || true
    ip6tables -t mangle -F 2>/dev/null || true
    ip6tables -t mangle -X 2>/dev/null || true
fi

ipset destroy allowed-domains 2>/dev/null || true
ipset destroy blocked-domains 2>/dev/null || true
ipset destroy allowed-domains-v6 2>/dev/null || true
ipset destroy blocked-domains-v6 2>/dev/null || true

# 2. Restore Docker DNS rules
if [ -n "$DOCKER_DNS_RULES" ]; then
    echo "Restoring Docker DNS rules..."
    iptables -t nat -N DOCKER_OUTPUT 2>/dev/null || true
    iptables -t nat -N DOCKER_POSTROUTING 2>/dev/null || true
    echo "$DOCKER_DNS_RULES" | while read -r line; do
        [ -z "$line" ] && continue
        eval "iptables -t nat $line" 2>/dev/null || true
    done
fi

if [ -n "$DOCKER_DNS_RULES_V6" ]; then
    echo "Restoring Docker IPv6 DNS rules..."
    ip6tables -t nat -N DOCKER_OUTPUT 2>/dev/null || true
    ip6tables -t nat -N DOCKER_POSTROUTING 2>/dev/null || true
    echo "$DOCKER_DNS_RULES_V6" | while read -r line; do
        [ -z "$line" ] && continue
        eval "ip6tables -t nat $line" 2>/dev/null || true
    done
fi

# 3. Base allowances
if ! command -v ipset >/dev/null 2>&1; then
    echo "ERROR: ipset is required but not installed"
    exit 1
fi

echo "Applying base allowances (DNS, SSH, loopback)..."
iptables -A OUTPUT -p udp --dport 53 -j ACCEPT
iptables -A INPUT -p udp --sport 53 -j ACCEPT
iptables -A OUTPUT -p tcp --dport 22 -j ACCEPT
iptables -A INPUT -p tcp --sport 22 -m state --state ESTABLISHED -j ACCEPT
iptables -A INPUT -i lo -j ACCEPT
iptables -A OUTPUT -o lo -j ACCEPT

if [ "$ENABLEIPV6" = "true" ]; then
    ip6tables -A OUTPUT -p udp --dport 53 -j ACCEPT
    ip6tables -A INPUT -p udp --sport 53 -j ACCEPT
    ip6tables -A OUTPUT -p tcp --dport 22 -j ACCEPT
    ip6tables -A INPUT -p tcp --sport 22 -m state --state ESTABLISHED -j ACCEPT
    ip6tables -A INPUT -i lo -j ACCEPT
    ip6tables -A OUTPUT -o lo -j ACCEPT
fi

# 4. Create ipsets
ipset create allowed-domains hash:net
if [ "$BLOCKTELEMETRY" = "true" ]; then
    ipset create blocked-domains hash:net
fi

if [ "$ENABLEIPV6" = "true" ]; then
    ipset create allowed-domains-v6 hash:net family inet6
    if [ "$BLOCKTELEMETRY" = "true" ]; then
        ipset create blocked-domains-v6 hash:net family inet6
    fi
fi

# 5. Resolve domains with retries
resolve_and_add() {
    _domain="$1"
    _ipset="$2"
    _qtype="${3:-A}"
    _attempts=0
    _max_attempts=3
    while [ "$_attempts" -lt "$_max_attempts" ]; do
        echo "Resolving $_domain ($_qtype)..."
        _ips=$(dig +noall +answer "$_qtype" "$_domain" | awk -v qt="$_qtype" '$4 == qt {print $5}')
        if [ -n "$_ips" ]; then
            break
        fi
        _attempts=$((_attempts + 1))
        if [ "$_attempts" -lt "$_max_attempts" ]; then
            echo "WARNING: Failed to resolve $_domain, retrying in 2s..."
            sleep 2
        fi
    done
    if [ -z "$_ips" ]; then
        echo "WARNING: Failed to resolve $_domain ($_qtype) after $_max_attempts attempts"
        return 0
    fi
    echo "$_ips" | while read -r _ip; do
        [ -z "$_ip" ] && continue
        ipset add "$_ipset" "$_ip" 2>/dev/null || true
    done
}

# 6. Resolve service tags from the installed registry
QUEUE=$(mktemp)
VISITED=$(mktemp)
DOMAINS_FILE=$(mktemp)
FETCH_URL_FILE=$(mktemp)

trap 'rm -f "$QUEUE" "$VISITED" "$DOMAINS_FILE" "$FETCH_URL_FILE"' EXIT

MAX_DEPTH=10

if [ -f "$REGISTRY" ]; then
    echo "Loading service registry from $REGISTRY"

    # Seed the queue with the requested tags (depth 0)
    printf '%s\n' "$SERVICES" | tr ',' '\n' | sed 's/^[[:space:]]*//;s/[[:space:]]*$//' | while read -r _tag; do
        [ -z "$_tag" ] && continue
        echo "0 $_tag" >> "$QUEUE"
    done

    while [ -s "$QUEUE" ]; do
        _line=$(head -n 1 "$QUEUE")
        _depth=${_line%% *}
        _tag=${_line#* }

        # Pop the first line
        tail -n +2 "$QUEUE" > "${QUEUE}.tmp"
        mv "${QUEUE}.tmp" "$QUEUE"

        [ -z "$_tag" ] && continue
        if [ "$_depth" -gt "$MAX_DEPTH" ]; then
            echo "WARNING: Exceeded maximum recursion depth resolving tag '$_tag'"
            continue
        fi
        if grep -qx "$_tag" "$VISITED" 2>/dev/null; then
            continue
        fi
        echo "$_tag" >> "$VISITED"

        if ! jq -e --arg t "$_tag" '.[$t]?' "$REGISTRY" >/dev/null 2>&1; then
            echo "WARNING: Unknown service tag '$_tag', skipping"
            continue
        fi

        _fetch_url=$(jq -r --arg t "$_tag" '.[$t].fetchIpRanges // empty' "$REGISTRY")
        if [ -n "$_fetch_url" ]; then
            echo "$_fetch_url" > "$FETCH_URL_FILE"
        fi

        # Recurse into composite tags
        jq -r --arg t "$_tag" 'if .[$t] | has("extends") then .[$t].extends[] else empty end' "$REGISTRY" | while read -r _ext; do
            [ -z "$_ext" ] && continue
            echo "$((_depth + 1)) $_ext" >> "$QUEUE"
        done

        # Collect direct domains
        jq -r --arg t "$_tag" '.[$t].domains[]?' "$REGISTRY" | while read -r _dom; do
            [ -z "$_dom" ] && continue
            if ! grep -qx "$_dom" "$DOMAINS_FILE" 2>/dev/null; then
                echo "$_dom" >> "$DOMAINS_FILE"
            fi
        done
    done
else
    echo "WARNING: Service registry not found at $REGISTRY; no service tags will be resolved"
fi

# 7. Add user-supplied extra domains
if [ -n "$EXTRADOMAINS" ]; then
    echo "Adding extra domains: $EXTRADOMAINS"
    printf '%s\n' "$EXTRADOMAINS" | tr ',' '\n' | sed 's/^[[:space:]]*//;s/[[:space:]]*$//' | while read -r _dom; do
        [ -z "$_dom" ] && continue
        if ! grep -qx "$_dom" "$DOMAINS_FILE" 2>/dev/null; then
            echo "$_dom" >> "$DOMAINS_FILE"
        fi
    done
fi

# 8. Fetch dynamic IP ranges advertised by any resolved tag
if [ -s "$FETCH_URL_FILE" ]; then
    _fetch_url=$(head -n 1 "$FETCH_URL_FILE")
    echo "Fetching dynamic IP ranges from $_fetch_url..."
    _attempts=0
    _max_attempts=3
    _ranges=""
    while [ "$_attempts" -lt "$_max_attempts" ]; do
        _ranges=$(curl -4 -s --connect-timeout 10 "$_fetch_url" || true)
        if [ -n "$_ranges" ]; then
            break
        fi
        _attempts=$((_attempts + 1))
        if [ "$_attempts" -lt "$_max_attempts" ]; then
            echo "WARNING: Failed to fetch IP ranges, retrying in 3s..."
            sleep 3
        fi
    done

    if [ -z "$_ranges" ]; then
        echo "WARNING: Failed to fetch IP ranges after $_max_attempts attempts, falling back to DNS resolution"
        resolve_and_add "github.com" "allowed-domains"
        resolve_and_add "api.github.com" "allowed-domains"
        if [ "$ENABLEIPV6" = "true" ]; then
            resolve_and_add "github.com" "allowed-domains-v6" "AAAA"
            resolve_and_add "api.github.com" "allowed-domains-v6" "AAAA"
        fi
    else
        if echo "$_ranges" | jq -e '.web and .api and .git' >/dev/null 2>&1; then
            echo "$_ranges" | jq -r '(.web + .api + .git)[]' | while read -r _cidr; do
                [ -z "$_cidr" ] && continue
                case "$_cidr" in
                    *:*)
                        if [ "$ENABLEIPV6" = "true" ]; then
                            ipset add allowed-domains-v6 "$_cidr" 2>/dev/null || true
                        fi
                        ;;
                    [0-9]*.[0-9]*.[0-9]*.[0-9]*/[0-9]*)
                        ipset add allowed-domains "$_cidr" 2>/dev/null || true
                        ;;
                    *)
                        echo "WARNING: Skipping invalid CIDR from IP range API: $_cidr"
                        ;;
                esac
            done
        else
            echo "WARNING: IP range API response missing expected fields"
        fi
    fi
fi

# 9. Resolve all collected allowed domains
if [ -s "$DOMAINS_FILE" ]; then
    echo "Resolving allowed domains..."
    sort -u "$DOMAINS_FILE" | while read -r _domain; do
        [ -z "$_domain" ] && continue
        resolve_and_add "$_domain" "allowed-domains"
        if [ "$ENABLEIPV6" = "true" ]; then
            resolve_and_add "$_domain" "allowed-domains-v6" "AAAA"
        fi
    done
fi

# 10. Block telemetry domains if requested
if [ "$BLOCKTELEMETRY" = "true" ]; then
    echo "Blocking telemetry domains..."
    for _domain in $TELEMETRY_DOMAINS; do
        resolve_and_add "$_domain" "blocked-domains"
        if [ "$ENABLEIPV6" = "true" ]; then
            resolve_and_add "$_domain" "blocked-domains-v6" "AAAA"
        fi
    done
fi

# 11. Host network detection
HOST_IP=$(ip route 2>/dev/null | grep default | awk '{print $3}' | head -n 1)
if [ -n "$HOST_IP" ]; then
    HOST_NETWORK=$(printf '%s' "$HOST_IP" | sed 's/\.[0-9]*$/.0\/24/')
    echo "Host network detected as: $HOST_NETWORK"
    iptables -A INPUT -s "$HOST_NETWORK" -j ACCEPT
    iptables -A OUTPUT -d "$HOST_NETWORK" -j ACCEPT
fi

if [ "$ENABLEIPV6" = "true" ]; then
    HOST_IPV6=$(ip -6 route 2>/dev/null | grep default | awk '{print $3}' | head -n 1)
    if [ -n "$HOST_IPV6" ]; then
        HOST_NETWORK_V6=$(printf '%s' "$HOST_IPV6" | awk -F: '{printf "%s:%s:%s:%s::/64\n", $1, $2, $3, $4}')
        echo "Host IPv6 network detected as: $HOST_NETWORK_V6"
        ip6tables -A INPUT -s "$HOST_NETWORK_V6" -j ACCEPT
        ip6tables -A OUTPUT -d "$HOST_NETWORK_V6" -j ACCEPT
    fi
fi

# 12. Apply policy
if [ "$POLICY" = "whitelist" ]; then
    echo "Applying whitelist policy..."
    if [ "$BLOCKTELEMETRY" = "true" ]; then
        iptables -I OUTPUT -m set --match-set blocked-domains dst -j DROP
    fi

    iptables -P INPUT DROP
    iptables -P FORWARD DROP
    iptables -P OUTPUT DROP

    iptables -A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT
    iptables -A OUTPUT -m state --state ESTABLISHED,RELATED -j ACCEPT

    iptables -A OUTPUT -m set --match-set allowed-domains dst -j ACCEPT
    iptables -A OUTPUT -j REJECT --reject-with icmp-admin-prohibited

    if [ "$ENABLEIPV6" = "true" ]; then
        if [ "$BLOCKTELEMETRY" = "true" ]; then
            ip6tables -I OUTPUT -m set --match-set blocked-domains-v6 dst -j DROP
        fi

        ip6tables -P INPUT DROP
        ip6tables -P FORWARD DROP
        ip6tables -P OUTPUT DROP

        ip6tables -A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT
        ip6tables -A OUTPUT -m state --state ESTABLISHED,RELATED -j ACCEPT

        ip6tables -A OUTPUT -m set --match-set allowed-domains-v6 dst -j ACCEPT
        ip6tables -A OUTPUT -j REJECT --reject-with icmp6-adm-prohibited
    fi

    echo "Firewall configured in whitelist mode"
else
    echo "Applying monitor policy (logging only)..."
    if [ "$BLOCKTELEMETRY" = "true" ]; then
        iptables -I OUTPUT -m set --match-set blocked-domains dst -j DROP
    fi
    iptables -A OUTPUT -m set ! --match-set allowed-domains dst -j LOG --log-prefix "FIREWALL-DROP: " --log-level 4

    if [ "$ENABLEIPV6" = "true" ]; then
        if [ "$BLOCKTELEMETRY" = "true" ]; then
            ip6tables -I OUTPUT -m set --match-set blocked-domains-v6 dst -j DROP
        fi
        ip6tables -A OUTPUT -m set ! --match-set allowed-domains-v6 dst -j LOG --log-prefix "FIREWALL-DROP-V6: " --log-level 4
    fi

    echo "Firewall configured in monitor mode (logging only)"
fi

echo "Container firewall activation complete"
RUNTIMEEOF

# Bake the build-time option values into the runtime script.
sed \
    -e "s#__SERVICES__#${SERVICES}#g" \
    -e "s#__EXTRADOMAINS__#${EXTRADOMAINS}#g" \
    -e "s#__BLOCKTELEMETRY__#${BLOCKTELEMETRY}#g" \
    -e "s#__POLICY__#${POLICY}#g" \
    -e "s#__ENABLEIPV6__#${ENABLEIPV6}#g" \
    "$TMP_RUNTIME" > "$SCRIPT_PATH"

chmod +x "$SCRIPT_PATH"

echo "Container Firewall feature installed"
echo "Firewall rules will be applied automatically at container start via postStartCommand"
