#!/bin/bash
set -e

# multi-arch-tuning install script
# Detects container architecture and sets environment variables.

ARCH="$(uname -m)"
OLLAMA_MODEL="__OLLAMAMODEL__"
PYTORCH_INDEX="__PYTORCHINDEX__"

# Architecture mapping
if [ "$ARCH" = "aarch64" ] || [ "$ARCH" = "arm64" ]; then
    ARCH_LABEL="arm64"
else
    ARCH_LABEL="amd64"
fi

# Auto-detect GPU availability
GPU_AVAILABLE="false"
if command -v nvidia-smi >/dev/null 2>&1 && nvidia-smi >/dev/null 2>&1; then
    GPU_AVAILABLE="true"
fi

# Determine Ollama model
if [ "$OLLAMA_MODEL" = "auto" ]; then
    if [ "$ARCH_LABEL" = "arm64" ]; then
        OLLAMA_MODEL="llama3.2:3b"
    else
        OLLAMA_MODEL="llama3.1:8b"
    fi
fi

# Determine PyTorch index
if [ "$PYTORCH_INDEX" = "auto" ]; then
    if [ "$GPU_AVAILABLE" = "true" ]; then
        PYTORCH_INDEX="https://download.pytorch.org/whl/cu124"
    else
        PYTORCH_INDEX="https://download.pytorch.org/whl/cpu"
    fi
fi

# Write environment configuration
cat > /usr/local/bin/multi-arch-tuning-env <<EOF
#!/bin/bash
# multi-arch-tuning environment variables
# Source this file or run: eval "\$(multi-arch-tuning-env)"

echo "export ARCH_LABEL=\"$ARCH_LABEL\""
echo "export OLLAMA_MODEL=\"$OLLAMA_MODEL\""
echo "export PYTORCH_INDEX=\"$PYTORCH_INDEX\""
echo "export UV_PYTHON_DOWNLOADS=\"$ARCH_LABEL\""
echo "export TORCH_INDEX_URL=\"$PYTORCH_INDEX\""
echo "export PIP_EXTRA_INDEX_URL=\"$PYTORCH_INDEX\""
EOF

chmod +x /usr/local/bin/multi-arch-tuning-env

# Install a shell profile snippet that sources the variables
cat > /etc/profile.d/multi-arch-tuning.sh <<EOF
# Auto-generated by multi-arch-tuning feature
eval "\$(/usr/local/bin/multi-arch-tuning-env)"
EOF

echo "multi-arch-tuning installed."
echo "  Architecture: $ARCH_LABEL"
echo "  Ollama model: $OLLAMA_MODEL"
echo "  PyTorch index: $PYTORCH_INDEX"
